apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.21.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/cert-manager/values.yaml
    - repoURL: git@github.com:SmigorX/homelab.git
      targetRevision: master
      ref: values
    - repoURL: git@github.com:SmigorX/homelab.git
      targetRevision: master
      path: cert-manager/manifests
      directory:
        recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
