apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: "1.5.1"
      helm:
        releaseName: vault-secrets-operator
        valueFiles:
          - $values/vault-secrets-operator/values.yaml
    - repoURL: git@github.com:SmigorX/homelab.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
