apiVersion: v1
kind: Service
metadata:
  name: joplin-postgres
  namespace: joplin
  labels:
    app.kubernetes.io/name: joplin
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: joplin
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres