apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: k3s-auth
  namespace: infisical-secrets-operator
spec:
  infisicalConnectionRef:
    name: selfhosted-infisical
    namespace: infisical-secrets-operator

  method: kubernetes

  kubernetes:
    identityIdRef:
      name: infisical-kubernetes-auth
      namespace: infisical-secrets-operator
      key: identity-id

    serviceAccountRef:
      name: infisical-secre-controller-manager
      namespace: infisical-secrets-operator