apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-data
  namespace: onlyoffice-docs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-core
  resources:
    requests:
      storage: 10Gi
