global:
  revisionHistoryLimit: 3

  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: AUTHENTIK_SECRET_KEY

    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: POSTGRES_PASSWORD

    - name: YAMTRACK_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: authentik-oidc-secrets
          key: yamtrack-client-secret

    - name: PAPERLESS_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: authentik-oidc-secrets
          key: paperless-client-secret

authentik:
  log_level: info

blueprints:
  configMaps:
    - authentik-blueprints

server:
  replicas: 1

  ingress:
    enabled: true
    ingressClassName: traefik

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Authentik
      gethomepage.dev/description: Identity provider and single sign-on
      gethomepage.dev/group: Platform
      gethomepage.dev/icon: authentik.png
      gethomepage.dev/href: https://auth.k8s.internal.smigorx.eu

    hosts:
      - auth.k8s.internal.smigorx.eu

    tls:
      - secretName: authentik-tls
        hosts:
          - auth.k8s.internal.smigorx.eu

  metrics:
    enabled: false

worker:
  replicas: 1

  metrics:
    enabled: false

geoip:
  enabled: false

prometheus:
  rules:
    enabled: false

postgresql:
  enabled: true

  auth:
    username: authentik
    database: authentik

    enablePostgresUser: false

    existingSecret: authentik-secrets
    secretKeys:
      userPasswordKey: POSTGRES_PASSWORD

  primary:
    persistence:
      enabled: true
      storageClass: local-path-core
      size: 8Gi
