infisical:
  replicaCount: 1

  kubeSecretRef: infisical-secrets

  autoBootstrap:
    enabled: false

ingress:
  enabled: true
  hostName: infisical.internal.smigorx.eu
  ingressClassName: traefik

  nginx:
    enabled: false

  tls: []

postgresql:
  enabled: true

redis:
  enabled: true
  cluster:
    enabled: false
  architecture: standalone

ingress-nginx:
  enabled: false