dex:
  enabled: false

notifications:
  enabled: false

redis:
  enabled: true

applicationSet:
  replicas: 1

controller:
  replicas: 1

repoServer:
  replicas: 1

server:
  replicas: 1

  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.k8s.internal.smigorx.eu
    path: /
    pathType: Prefix
    tls: true

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/service.serversscheme: http

global:
  domain: argocd.k8s.internal.smigorx.eu

configs:
  params:
    server.insecure: true
