dex:
  enabled: false

notifications:
  enabled: false

redis:
  enabled: true

applicationSet:
  replicas: 1

controller:
  replicas: 1

repoServer:
  replicas: 1

server:
  replicas: 1

  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.k8s.internal.smigorx.eu
    path: /
    pathType: Prefix
    tls: true

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Infrastructure
      gethomepage.dev/name: Argo CD
      gethomepage.dev/description: GitOps continuous delivery
      gethomepage.dev/icon: argocd.png
      gethomepage.dev/href: https://argocd.k8s.internal.smigorx.eu
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/service.serversscheme: http

global:
  domain: argocd.k8s.internal.smigorx.eu

configs:
  cm:
    url: https://argocd.k8s.internal.smigorx.eu
    oidc.config: |
      name: Authentik
      issuer: https://auth.k8s.internal.smigorx.eu/application/o/argocd/
      clientID: argocd
      enablePKCEAuthentication: true
      requestedScopes: ["openid", "profile", "email"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, authentik Admins, role:admin
    scopes: "[groups, email]"
  params:
    server.insecure: true
