apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  argocd.yaml: |
    version: 1
    metadata:
      name: Argo CD OIDC application
      labels:
        blueprints.goauthentik.io/description: Argo CD single sign-on configuration
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        id: argocd-provider
        identifiers:
          name: argocd
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: public
          client_id: argocd
          redirect_uris:
            - matching_mode: strict
              url: https://argocd.k8s.internal.smigorx.eu/pkce/verify
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      - model: authentik_core.application
        identifiers:
          slug: argocd
        attrs:
          name: Argo CD
          group: Infrastructure
          meta_launch_url: https://argocd.k8s.internal.smigorx.eu
          provider: !KeyOf argocd-provider
  joplin.yaml: |
    version: 1
    metadata:
      name: Joplin SAML application
      labels:
        blueprints.goauthentik.io/description: Joplin single sign-on configuration
    entries:
      - model: authentik_providers_saml.samlprovider
        id: joplin-provider
        identifiers:
          name: joplin
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          acs_url: https://joplin.internal.smigorx.eu/api/saml
          audience: joplin
          sp_binding: post
          signing_kp: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      - model: authentik_core.application
        identifiers:
          slug: joplin
        attrs:
          name: Joplin
          group: Applications
          meta_launch_url: https://joplin.internal.smigorx.eu
          provider: !KeyOf joplin-provider
