apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: workloads

  source:
    repoURL: git@github.com:SmigorX/homelab.git
    targetRevision: master
    path: nextcloud/manifests
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
