apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-data
  namespace: yamtrack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-core
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-redis-data
  namespace: yamtrack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-core
  resources:
    requests:
      storage: 1Gi
