apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-core
  resources:
    requests:
      storage: 50Gi